### ISSUE TITLE
Need support for v4

### ISSUE THREAD

**Issue by kurilov** [pangpanglabs/echoswagger#33]
Current stable versoin for echo is 4.
Current echoswagger used v3 and i got error 

`cannot use e (type *"github.com/labstack/echo/v4".Echo) as type *"github.com/labstack/echo".Echo in argument to echoswagger.New`

**Comment by elvinchan** [comment]
@kurilov Thanks for your feedback.
I have released v2 version, which uses Echo v4.
Please try `go get github.com/pangpanglabs/echoswagger/v2`
(Need Go modules enabled)
