### ISSUE TITLE
How to set Tag for operations?

### ISSUE THREAD

**Issue by chinajuanbob** [pangpanglabs/echoswagger#36]
For instance, if I want to group `/api/v1/user` and `/api/v1/users` in the tag `user`, and group `/api/v1/book` and `/api/v1/books` in the tag `book` at the same time. How could I code this with v2?

Thanks a lot!

**Comment by elvinchan** [comment]
@chinajuanbob Thanks for your feedback!
I released a new version `v2.1.0`, which allows same Tag for multiple groups.
Please have a try ^^
