### ISSUE TITLE
Why model has XML definition?

### ISSUE THREAD

**Issue by aclowkey** [pangpanglabs/echoswagger#38]
The model section in the doc has XML definition, when I'm not using XML at all.
Any way to make it JSON? 
```
xml: OrderedMap { "name": "Total" }
xml:
   name: Total
```

**Comment by elvinchan** [comment]
@aclowkey What do you mean "way to make it JSON"? 

If you want to remove XML properties from swagger.json, yes, maybe we can change this in the future

**Comment by eloo** [comment]
Hi, is there any update for this? 
I would also like to use json as a model definition.

Thanks

**Comment by elvinchan** [comment]
@eloo It's no problem to use JSON as model definition. This issus is about redundent XML definition in swagger.json, which I think is not your concern.

**Comment by eloo** [comment]
and how can i disable the XML?
