### ISSUE TITLE
How to nest groups?

### ISSUE THREAD

**Issue by eloo** [pangpanglabs/echoswagger#41]
Hi,
i'm currently try to adjust my code to use echoswagger for automatic swagger generation but it seems like nesting of groups is not possible.
Or maybe i just missed it somehow or is this by design? 

What i want to do is something like this
```
	apiRoot := echoswagger.New(echo.New(), "/doc", nil)

	rootGroup := apiRoot.Group("root", "/")

	apiGroup := rootGroup.Group("api", "api/")
```
But the `apiGroup := rootGroup.Group("api", "api/")` is not going to work as echoswagger.ApiGroup does not have a Group method.
If i would use `rootGroup.EchoGroup().Group(...)` i will loose the swagger generation.

Do you have any ideas about this?

Thanks
eloo

**Comment by elvinchan** [comment]
@eloo This is by design. According to https://swagger.io/docs/specification/grouping-operations-with-tags/ Swagger is not allowed nested tags currently, and tags in Swagger specification is corresponds to groups in Echo. So unfortunately, it is impossible to use nested groups when using Echoswagger.

**Comment by eloo** [comment]
okay..  and why is echoswagger here so limited? 
what about allowing generating my API using echo and afterwards assign echo groups to echoswagger groups? 

for example something like this
```
e := echo.New()
swaggerRoot := echoswagger.New(e, "/doc", nil)
apiGroup := e.Group("/api")
v1Group := apiGroup.Group("/v1")

v1SwaggerGroup := swaggerRoot.BindGroup(v1Group)
```

this would bring the flexibility echo groups back and would enable swagger as well.

currently its more like that i need to adjust my api structure only to make echoswagger work. that doesn't feel like good design to me and makes maintenance of APIs a bit weird.

best regards

**Comment by elvinchan** [comment]
@eloo Nice suggestion, I will take a closer look

**Comment by eloo** [comment]
sounds good.. i guess this would make the library more flexible..

**Comment by elvinchan** [comment]
@eloo I added BindGroup(), please try

**Comment by eloo** [comment]
@elvinchan just tested it.. 
looks good and works as expected. thanks

**Comment by rodinv** [comment]
this method is not available in v2 version?

**Comment by elvinchan** [comment]
@rodinv It's already available in v2. Please check if you are using the newest version, or just try
`go get -u github.com/pangpanglabs/echoswagger/v2`
